@startuml
namespace Application {
    enum InitType {
        LOAD
        GENERATE
    }

    class Render {
        - currentScene: Domain.Scene
        - gamePlot: Domain.Plot
        - tileEngine: Infrastructure.TileEngine
        + initScene(initType: InitType, sceneIdent: String)
        + computeChange(input: Presentation.InputAction)
        + killScene()
        + render(buf: Presentation.Screen.buffer, input: Presentation.Input)
        - renderMap(buf: Presentation.Screen.buffer, input: Presentation.Input)
        - renderEntities(buf: Presentation.Screen.buffer, input: Presentation.Input)
        - renderItems(buf: Presentation.Screen.buffer, input: Presentation.Input)
    }

    Render ..> InitType : <<use>>
}
@enduml
